# Generated by Django 3.1 on 2022-01-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Number', models.IntegerField(max_length=50)),
            ],
        ),
    ]
