# Generated by Django 3.1 on 2022-01-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Number',
            field=models.CharField(max_length=50),
        ),
    ]
